### ISSUE TITLE
Add link to live site in repo header

### ISSUE THREAD

**Issue by nihonjinrxs** [tomquisel/clinical-trials-report-frontend#26]
If you edit the description of the repo (click on the description just under the repo name at the top of the page), you can add a web link. Linking to the live site would help with discoverability. 

Also, in the same area, I think you can tag the site with keywords so that it shows up in Github searches for a topic. That might be a good idea too.

**Comment by tomquisel** [comment]
Great call! I added a link & some tags. Super helpful suggestion 😄
